In [1]:
import cv2
import numpy as np

In [19]:
img=cv2.imread("Amazon.png")
#img=cv2.resize(img,512,512)

gray_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
ret,threshold=cv2.threshold(gray_img,20,255,0)

contours,hierarchy=cv2.findContours(threshold,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
print("number of contours= "+str(len(contours)))
print(contours[0])

cv2.drawContours(img,contours,-1,(255,255,0),4)
cv2.imshow('image',img)
cv2.imshow('image gray',gray_img)
cv2.imshow('threshold',threshold)

cv2.waitKey(0)

cv2.destroyAllWindows()

number of contours= 8
[[[281 526]]

 [[280 527]]

 [[280 530]]

 [[285 535]]

 [[286 535]]

 [[291 540]]

 [[292 540]]

 [[296 544]]

 [[297 544]]

 [[300 547]]

 [[301 547]]

 [[303 549]]

 [[304 549]]

 [[306 551]]

 [[307 551]]

 [[309 553]]

 [[310 553]]

 [[312 555]]

 [[313 555]]

 [[315 557]]

 [[316 557]]

 [[317 558]]

 [[318 558]]

 [[320 560]]

 [[321 560]]

 [[322 561]]

 [[323 561]]

 [[325 563]]

 [[326 563]]

 [[327 564]]

 [[328 564]]

 [[329 565]]

 [[330 565]]

 [[331 566]]

 [[332 566]]

 [[333 567]]

 [[334 567]]

 [[335 568]]

 [[336 568]]

 [[337 569]]

 [[338 569]]

 [[339 570]]

 [[340 570]]

 [[341 571]]

 [[342 571]]

 [[343 572]]

 [[345 572]]

 [[346 573]]

 [[347 573]]

 [[348 574]]

 [[349 574]]

 [[350 575]]

 [[352 575]]

 [[353 576]]

 [[355 576]]

 [[356 577]]

 [[357 577]]

 [[358 578]]

 [[360 578]]

 [[361 579]]

 [[363 579]]

 [[364 580]]

 [[366 580]]

 [[367 581]]

 [[369 581]]

 [[370 582]]

 [[372 582]]

 [[373 583]]

 [[376 583]]

 [[377 584]]